### ISSUE TITLE
Can't download data from Scale AI

### ISSUE THREAD

**Issue by ekwska** [scaleapi/pandaset-devkit#70]
# Summary
I have tried to download the PandaSet data from [Scale AI](https://scale.com/resources/download/pandaset), but after clicking the download button all that opens is an empty white floating box with the header 'Download Dataset' that doesn't contain any links or redirect. This happens even after I sign in. 

It looks like the website is broken, I'm not sure if anyone else is getting this issue.

Are there any other ways to access this data, for example direct download links, URLs or links to where it is hosted on ScaleAI? Thanks.

# Tested on
* Ubuntu 18.04
* Windows 10 
* Latest Chrome
* Latest Firefox

**Comment by ekwska** [comment]
I am closing this issue, as I got in contact with the Scale AI team who fixed the bug on the site. The dataset download links are live again and I was able to submit the forms for the data.

**Comment by mhung-hust** [comment]
me too
