### ISSUE TITLE
Sensors: extrinsic calibration coordinate system

### ISSUE THREAD

**Issue by jlbslbs** [scaleapi/pandaset-devkit#71]
There is the file [docs/static_extrinsic_calibration.yaml](https://github.com/scaleapi/pandaset-devkit/blob/f7447e0581546e0cee0cf4c15b71891c9c1a6396/docs/static_extrinsic_calibration.yaml), which holds the mounting position (extrinsic calibration) of the sensors.

If I look, for example, at the _main_pandar64_ sensor, its mounting position is the unity transformation, which means that the mounting position coordinate system equals the _main_pandar64_ sensor coordinate system, i.e. has its origin at this sensor. What is, however, the transformation from the mounting position coordinate system to the ego coordinate system, which has its origin at the middle of the rear axis?

**Comment by xpchuan-95** [comment]
There are Lidar frame, ego frame and world frame, you can use this yaml file to figure out the relative extrinsic pose between two sensors. If you want to get raw Lidar points you can transform points to camera frame first and then use this calibration file to transform points in camera frame to "main_pandar64" or "front_gt", the calibration is done under static situation.
