### ISSUE TITLE
Bounding box for 2D detection

### ISSUE THREAD

**Issue by GEngels** [scaleapi/pandaset-devkit#79]
First off, thanks for the great dataset!

I would like to use the front camera images to train a network for regular object detection on camera images with 2D bounding boxes. You provide the cuboids and projection in the camera image, but would it also be possible to obtain a 2D bounding for the images?

**Comment by xpchuan-95** [comment]
sorry, there is no annotated 2d bounding box.

**Comment by GEngels** [comment]
okay clear, thank you for the response
